export const FETCH_MOVIES_REQUEST = 'FETCH_MOVIES_REQUEST';
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
export const FETCH_MOVIES_FAILURE = 'FETCH_MOVIES_FAILURE';

export const ADD_MOVIE = 'ADD_MOVIE';
export const MOVIE_FETCHED = 'MOVIE_FETCHED';
export const MOVIE_UPDATED = 'MOVIE_UPDATED';
export const MOVIE_DELETED = 'MOVIE_DELETED';
export const MOVIE_SELECTED = 'MOVIE_SELECTED';

export const SEARCH_MOVIES = 'SEARCH_MOVIES';
export const SWITCH_FILTER = 'SWITCH_FILTER';